export const sampleAlerts = [
  {
    id: "a1",
    name: "Earthquakes in Japan",
    type: "earthquake",
    location: "Japan",
    radius: 300,
    severity: "moderate",
    channels: ["app", "email"],
    active: true,
  },
  {
    id: "a2",
    name: "California Wildfires",
    type: "fire",
    location: "California, USA",
    radius: 150,
    severity: "high",
    channels: ["app"],
    active: true,
  },
  {
    id: "a3",
    name: "Southeast Asia Flooding",
    type: "flood",
    location: "Southeast Asia",
    radius: 500,
    severity: "any",
    channels: ["app", "email", "sms"],
    active: true,
  },
  {
    id: "a4",
    name: "Hurricane Atlantic",
    type: "hurricane",
    location: "Atlantic Ocean",
    radius: 800,
    severity: "high",
    channels: ["app", "email"],
    active: false,
  },
  {
    id: "a5",
    name: "Tornado Midwest",
    type: "tornado",
    location: "Midwest USA",
    radius: 200,
    severity: "any",
    channels: ["app"],
    active: true,
  },
];