export const responders = [
  {
    id: "resp-1",
    name: "Medical Team Alpha",
    type: "Medical",
    members: 8,
    location: "Central District",
    status: "available",
    lastDeployed: "2 days ago",
    specialization: "Emergency Medicine",
    contact: "John Wilson",
    phone: "+1 (555) 123-4567",
    readiness: 100,
    equipmentStatus: "complete",
  },
  {
    id: "resp-2",
    name: "Search & Rescue Team 3",
    type: "Search & Rescue",
    members: 12,
    location: "North District",
    status: "deployed",
    lastDeployed: "Currently deployed",
    specialization: "Urban Search & Rescue",
    contact: "Maria Rodriguez",
    phone: "+1 (555) 234-5678",
    readiness: 85,
    equipmentStatus: "partial",
  },
  {
    id: "resp-3",
    name: "Firefighting Unit Delta",
    type: "Firefighting",
    members: 15,
    location: "East District",
    status: "available",
    lastDeployed: "1 week ago",
    specialization: "Wildfire Response",
    contact: "Robert Chen",
    phone: "+1 (555) 345-6789",
    readiness: 95,
    equipmentStatus: "complete",
  },
  {
    id: "resp-4",
    name: "Supply Distribution Team",
    type: "Logistics",
    members: 6,
    location: "South District",
    status: "standby",
    lastDeployed: "3 days ago",
    specialization: "Relief Supplies",
    contact: "Sarah Johnson",
    phone: "+1 (555) 456-7890",
    readiness: 90,
    equipmentStatus: "complete",
  },
  {
    id: "resp-5",
    name: "Technical Rescue Squad",
    type: "Technical Rescue",
    members: 10,
    location: "West District",
    status: "maintenance",
    lastDeployed: "5 days ago",
    specialization: "Structural Collapse",
    contact: "David Patel",
    phone: "+1 (555) 567-8901",
    readiness: 70,
    equipmentStatus: "undergoing maintenance",
  },
  {
    id: "resp-6",
    name: "Flood Response Team",
    type: "Water Rescue",
    members: 9,
    location: "River District",
    status: "available",
    lastDeployed: "2 weeks ago",
    specialization: "Swift Water Rescue",
    contact: "Lisa Nguyen",
    phone: "+1 (555) 678-9012",
    readiness: 100,
    equipmentStatus: "complete",
  },
  {
    id: "resp-7",
    name: "Mobile Medical Unit",
    type: "Medical",
    members: 7,
    location: "Central District",
    status: "deployed",
    lastDeployed: "Currently deployed",
    specialization: "Field Hospital",
    contact: "Michael Barnes",
    phone: "+1 (555) 789-0123",
    readiness: 90,
    equipmentStatus: "partial",
  },
];
export const teamDeploymentSchedule = [
  {
    team: "Search & Rescue Team 3",
    event: "Japan Earthquake Response",
    date: "Mar 22, 2025",
    status: "Scheduled",
  },
  {
    team: "Medical Team Alpha",
    event: "Hurricane Preparation",
    date: "Mar 25, 2025",
    status: "Tentative",
  },
  {
    team: "Flood Response Team",
    event: "Monsoon Season Preparation",
    date: "Apr 5, 2025",
    status: "Planned",
  },
]
export const recentTeamActivities = [
  {
    team: "Medical Team Alpha",
    activity: "Completed emergency medical response training",
    date: "Mar 15, 2025",
    type: "Training",
  },
  {
    team: "Firefighting Unit Delta",
    activity: "Returned from Wildfire Response Mission",
    date: "Mar 14, 2025",
    type: "Deployment",
  },
  {
    team: "Technical Rescue Squad",
    activity: "Equipment maintenance and inspection",
    date: "Mar 16, 2025",
    type: "Maintenance",
  },
  {
    team: "Supply Distribution Team",
    activity: "Prepared supplies for Japan deployment",
    date: "Mar 19, 2025",
    type: "Preparation",
  },
]
export const equipmentInventoryStatus = [
  {
    category: "Medical Supplies",
    available: 85,
    total: 100,
    status: "Adequate",
  },
  {
    category: "Search & Rescue Equipment",
    available: 32,
    total: 40,
    status: "Adequate",
  },
  {
    category: "Communication Devices",
    available: 18,
    total: 25,
    status: "Limited",
  },
  {
    category: "Vehicles",
    available: 12,
    total: 15,
    status: "Adequate",
  },
  {
    category: "Personal Protective Equipment",
    available: 95,
    total: 120,
    status: "Adequate",
  },
  {
    category: "Water Rescue Equipment",
    available: 15,
    total: 20,
    status: "Adequate",
  },
  {
    category: "Power Generators",
    available: 6,
    total: 10,
    status: "Limited",
  },
  {
    category: "Food & Water Supplies",
    available: 3500,
    total: 5000,
    status: "Adequate",
  },
]