export const sampleDisasterList: Disaster[] = [
  {
    id: 1,
    type: "earthquake",
    title: "6.2 Magnitude Earthquake",
    location: [35.6762, 139.6503],
    severity: "high",
    status: "active",
    description: "Strong earthquake detected off the coast of Japan",
    timestamp: new Date().toISOString(),
  },
  {
    id: 2,
    type: "flood",
    title: "Severe Flooding",
    location: [12.6392, 101.4215],
    severity: "severe",
    status: "active",
    description: "Major flooding affecting multiple provinces",
    timestamp: new Date().toISOString(),
  },
  {
    id: 3,
    type: "fire",
    title: "Forest Fire",
    location: [37.7749, -122.4194],
    severity: "high",
    status: "active",
    description: "Large wildfire spreading rapidly",
    timestamp: new Date().toISOString(),
  },
  {
    id: 4,
    type: "flood",
    title: "Monsoon Flooding",
    location: [19.0760, 72.8777],
    severity: "high",
    status: "active",
    description: "Heavy monsoon rainfall causing widespread flooding in Mumbai and surrounding areas",
    timestamp: new Date().toISOString(),
  },
  {
    id: 5,
    type: "landslide",
    title: "Himalayan Landslide",
    location: [30.7333, 79.0667],
    severity: "severe",
    status: "active",
    description: "Major landslide in Uttarakhand blocking key roads and affecting multiple villages",
    timestamp: new Date().toISOString(),
  },
  {
    id: 6,
    type: "cyclone",
    title: "Cyclone Amphan",
    location: [22.5726, 88.3639],
    severity: "severe",
    status: "monitoring",
    description: "Powerful cyclone approaching Eastern coast with winds exceeding 160 km/h",
    timestamp: new Date().toISOString(),
  },

  {
    id: 7,
    type: "earthquake",
    title: "5.8 Magnitude Earthquake",
    location: [27.7172, 85.3240],
    severity: "moderate",
    status: "monitoring",
    description: "Earthquake in Nepal causing structural damage in multiple districts",
    timestamp: new Date().toISOString(),
  },
  {
    id: 8,
    type: "drought",
    title: "Severe Drought",
    location: [23.8103, 90.4125],
    severity: "high",
    status: "active",
    description: "Prolonged drought affecting agricultural regions and water supplies",
    timestamp: new Date().toISOString(),
  },
  {
    id: 9,
    type: "tsunami",
    title: "Tsunami Warning",
    location: [8.7832, 78.2003],
    severity: "high",
    status: "warning",
    description: "Tsunami warning issued after undersea seismic activity in the Indian Ocean",
    timestamp: new Date().toISOString(),
  },
]