"use client";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import {
  NewsAnalysis,
  analyzeNewsArticle,
} from "@/services/news-analysis-service";
import { NewsItem } from "@/types/news";
import { motion } from "framer-motion";
import { AlertTriangle, Check, X } from "lucide-react";
import { useState } from "react";

interface NewsAnalysisProps {
  news: NewsItem;
}

export default function NewsAnalysisComponent({ news }: NewsAnalysisProps) {
  const [analysis, setAnalysis] = useState<NewsAnalysis>(() =>
    analyzeNewsArticle(news)
  );

  return (
    <Card className="shadow-md">
      <CardHeader>
        <CardTitle className="text-lg">AI Analysis</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-col space-y-1">
          <div className="flex justify-between items-center">
            <span className="text-sm font-medium">Disaster Relevance</span>
            <div className="flex items-center space-x-2">
              <span className="text-sm font-medium">
                {analysis.relevanceScore}%
              </span>
            </div>
          </div>
          <Progress value={analysis.relevanceScore} />
        </div>

        <div className="flex justify-between">
          <div className="flex items-center space-x-2">
            <span className="text-sm font-medium">Reliability:</span>
            <Badge
              variant="outline"
              className={`
              ${
                analysis.reliability === "high"
                  ? "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300"
                  : analysis.reliability === "medium"
                  ? "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300"
                  : "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300"
              }
            `}
            >
              {analysis.reliability === "high" && (
                <Check className="h-3 w-3 mr-1" />
              )}
              {analysis.reliability === "low" && <X className="h-3 w-3 mr-1" />}
              {analysis.reliability === "medium" && (
                <AlertTriangle className="h-3 w-3 mr-1" />
              )}
              {analysis.reliability}
            </Badge>
          </div>

          <div className="flex items-center space-x-2">
            <span className="text-sm font-medium">Sentiment:</span>
            <Badge
              variant="outline"
              className={`
              ${
                analysis.sentiment === "positive"
                  ? "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300"
                  : analysis.sentiment === "negative"
                  ? "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300"
                  : "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300"
              }
            `}
            >
              {analysis.sentiment}
            </Badge>
          </div>
        </div>

        {analysis.keyPoints.length > 0 && (
          <div className="mt-4">
            <h4 className="text-sm font-medium mb-2">Key Points:</h4>
            <ul className="space-y-2">
              {analysis.keyPoints.map((point, index) => (
                <motion.li
                  key={index}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className="text-sm bg-muted p-2 rounded"
                >
                  {point}
                </motion.li>
              ))}
            </ul>
          </div>
        )}

        <div className="flex flex-col space-y-1 mt-2">
          <div className="flex justify-between items-center">
            <span className="text-sm font-medium">Controversy Level</span>
            <span className="text-sm">{analysis.controversyScore}%</span>
          </div>
          <Progress value={analysis.controversyScore} className="bg-muted" />
        </div>

        <div className="text-xs text-muted-foreground mt-4">
          <p>
            This analysis is generated by an AI model and should be used as a
            general guide only.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
